base/urls.py
from django.urls import path
from . import views
from patient_info_API.views import PatientListAPIView

app_name = 'base'

urlpatterns = [
    path('',PatientListAPIView.as_view(),name='index'),
    path('<int:Patient_id>/', views.detail, name='detail'),
    path('create_patient/',views.create_patient,name='create_patient'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from base import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('base/', include('base.urls')),
    path('common/', include('common.urls')),
    path('',views.index, name='index'),
    path('rest/', include('patient_info_API.urls')),
]

base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Patient 모델 정의
class Patient(models.Model):
    id = models.AutoField(primary_key=True)  # id 필드를 다시 추가
    last_name = models.CharField(max_length=50, null=False)
    first_name = models.CharField(max_length=50, null=False)
    birth_date = models.DateField(null=False)
    address = models.CharField(max_length=255, null=False)
    GENDER_CHOICES = [
        ('M', '남성'),
        ('F', '여성'),
    ]
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, null=False)
    phone_num = models.CharField(max_length=15, null=False)
    email = models.CharField(max_length=100, null=True)
    image = models.CharField(max_length=50, null=True)

    def __str__(self):
        return self.first_name


# User 모델 정의
class User(models.Model):
    id = models.AutoField(primary_key=True)  # id 필드를 다시 추가
    user_id = models.CharField(max_length=15, null=False)
    user_pw = models.CharField(max_length=100, null=False)
    name = models.CharField(max_length=50, null=False)
    birth_date = models.DateField(null=False)
    address = models.CharField(max_length=255, null=False)
    GENDER_CHOICES = [
        ('M', '남성'),
        ('F', '여성'),
    ]
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, null=False)
    phone_num = models.CharField(max_length=15, null=False)
    email = models.CharField(max_length=100, null=True)
    department = models.CharField(max_length=50, null=True)
    position = models.CharField(max_length=50, null=True)
    ROLE_CHOICES = [
        ('관리자', '관리자'),
        ('의사', '의사'),
        ('물리 치료사', '물리 치료사'),
        ('기타 의료진', '기타 의료진'),
        ('환자', '환자'),
        ('간호사', '간호사'),
    ]
    role = models.CharField(max_length=10, choices=ROLE_CHOICES, null=False)

    def __str__(self):
        return self.user_id

# 진료 데이터 모델 정의
class MedicalRecord(models.Model):
    id = models.AutoField(primary_key=True)  # 진료 기록번호, 자동 생성 필드
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)  # 환자와의 외래키 관계
    staff = models.ForeignKey(User, on_delete=models.CASCADE)  # 진료 담당 직원과의 외래키 관계
    date = models.DateField()  # 진료 일자, 날짜 필드
    symptoms = models.CharField(max_length=255)  # 증상, 문자열 필드
    diagnosis = models.CharField(max_length=255)  # 진단, 문자열 필드
    notes = models.TextField()  # 특이사항, 긴 텍스트 필드
    prescription_code = models.IntegerField()  # 약처방 코드 (향후 약처방 데이터 모델로 변경 가능)

    def __str__(self):
        return f"{self.patient.first_name}의 진료 기록"  # 문자열 표현을 정의한 메서드


# 처방 데이터 모델 정의
class Prescription(models.Model):
    prescription_code = models.AutoField(primary_key=True)  # 처방 코드, 자동 생성 필드
    medical_record = models.ForeignKey('MedicalRecord', on_delete=models.CASCADE)  # 진료 기록과의 외래키 관계
    medication_name = models.CharField(max_length=100)  # 처방 약 명, 문자열 필드
    total_dosage = models.DecimalField(max_digits=10, decimal_places=2)  # 총 투여량, 실수 필드
    frequency = models.IntegerField()  # 투여 횟수, 정수 필드
    duration_days = models.IntegerField()  # 투여 기간(일수), 정수 필드
    unit = models.CharField(max_length=20)  # 단위, 문자열 필드

    def __str__(self):
        return f"{self.medical_record.patient.first_name}의 처방 기록"  # 문자열 표현을 정의한 메서드

# 검사데이터 모델 정의
class ExaminationData(models.Model):
    record_number = models.AutoField(primary_key=True)  # 검사 기록번호, 자동 생성 필드
    patient = models.ForeignKey('Patient', on_delete=models.CASCADE)  # 환자 고유번호, 외래키 관계
    bone_mass = models.DecimalField(max_digits=10, decimal_places=2)  # 골결근량, 실수 필드
    body_fat = models.DecimalField(max_digits=5, decimal_places=2)  # 체지방량, 실수 필드
    muscle_strength = models.DecimalField(max_digits=5, decimal_places=2)  # 근지구력, 실수 필드
    cardiovascular_endurance = models.DecimalField(max_digits=5, decimal_places=2)  # 심폐지구력, 실수 필드
    agility = models.DecimalField(max_digits=5, decimal_places=2)  # 민첩성, 실수 필드
    flexibility = models.DecimalField(max_digits=5, decimal_places=2)  # 유연성, 실수 필드
    unique_number = models.CharField(max_length=50)  # 자료고유번호, 문자열 필드
    date = models.DateField()  # 검사 일자, 날짜 필드

    def __str__(self):
        return f"{self.patient.first_name}의 검사 데이터 기록"

# 치료데이터 모델 정의
class TreatmentData(models.Model):
    treatment_code = models.AutoField(primary_key=True)  # 치료코드, 자동 생성 필드
    medical_record = models.ForeignKey('MedicalRecord', on_delete=models.CASCADE)  # 진료코드(진료데이터 외래키)
    date = models.DateField()  # 일자, 날짜 필드
    therapy_type = models.CharField(max_length=50)  # 치료 종류, 문자열 필드
    therapy_days = models.IntegerField()  # 치료 일수, 정수 필드
    therapy_time = models.IntegerField()  # 치료 시간, 정수 필드

    def __str__(self):
        return f"{self.medical_record.patient.first_name}의 치료 기록"

# 운동데이터 모델 정의
class ExerciseData(models.Model):
    exercise_code = models.AutoField(primary_key=True)  # 운동 코드, 자동 생성 필드
    medical_record = models.ForeignKey('MedicalRecord', on_delete=models.CASCADE)  # 진료코드(진료데이터 외래키)
    date = models.DateField()  # 일자, 날짜 필드
    repetitions = models.IntegerField()  # 횟수, 정수 필드
    weight = models.DecimalField(max_digits=10, decimal_places=2)  # 중량, 실수 필드
    time = models.DecimalField(max_digits=5, decimal_places=2)  # 시간, 실수 필드
    speed = models.DecimalField(max_digits=5, decimal_places=2)  # 속도, 실수 필드
    distance = models.DecimalField(max_digits=10, decimal_places=2)  # 거리, 실수 필드
    exercise_type = models.CharField(max_length=50)  # 운동종류, 문자열 필드

    def __str__(self):
        return f"{self.medical_record.patient.first_name}의 운동 기록"

base/forms.py
from django import forms
from .models import Patient

class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient  # 사용할 모델
        fields = ['last_name', 'first_name', 'birth_date', 'address', 'gender', 'phone_num', 'email', 'image']

base/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Patient
from .forms import PatientForm
from rest_framework.views import APIView
from patient_info_API.views import PatientListAPIView

def index(request):
    patient_list = Patient.objects.order_by('last_name', 'first_name')
    context = {'patient_list': patient_list}
    return render(request, 'base/patient_list.html', context)

def detail(request, Patient_id):
    patient = Patient.objects.get(id=Patient_id)
    context = {'patient' : patient}
    return render(request, 'base/patient_detail.html',context)

def create_patient(request):
    if request.method == 'POST':
        form = PatientForm(request.POST)
        if form.is_valid():
            patient = form.save(commit=False)
            patient.save()
            return redirect('base:index')
    else:
        form = PatientForm()
    context = {'form': form}
    return render(request, 'base/patient_form.html', context)

templates/base/patient_detail.html
{% extends 'basic.html' %}
{% block content %}
<h1>Patient Detail</h1>
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <img src="{{ patient.image }}" alt="{{ patient.last_name }} {{ patient.first_name }}" class="img-fluid">
        </div>
        <div class="col-md-8">
            <h2>{{ patient.last_name }} {{ patient.first_name }}</h2>
            <dl class="row">
                <dt class="col-md-3">생년월일:</dt>
                <dd class="col-md-9">{{ patient.birth_date }}</dd>

                <dt class="col-md-3">성별:</dt>
                <dd class="col-md-9">{{ patient.get_gender_display }}</dd>

                <dt class="col-md-3">주소:</dt>
                <dd class="col-md-9">{{ patient.address }}</dd>

                <dt class="col-md-3">전화번호:</dt>
                <dd class="col-md-9">{{ patient.phone_num }}</dd>

                {% if patient.email %}
                <dt class="col-md-3">이메일:</dt>
                <dd class="col-md-9">{{ patient.email }}</dd>
                {% endif %}
            </dl>
        </div>
    </div>
</div>
{% endblock %}

templates/base/patient_form.html
{% extends 'basic.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">환자등록</h5>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/base/patient_list.html
{% extends 'basic.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <!-- 좌측 영역 - 사용자(의사) 정보 -->
            <div class="col-md-3">
                <div class="user-info">
                    <!-- 사용자 정보를 여기에 표시 -->
                </div>
            </div>

            <!-- 우측 영역 - 환자 목록 -->
            <div class="row">
                <!-- 우측 영역 - 환자 목록 -->
                <div class="col-md-6">
                    <div class="scrollable-list">
                        <div class="table-container table-responsive">
                            {% if patient_list %}
                                <table class="table table-bordered table-hover table-sm"> <!-- table-sm 클래스 추가 -->
                                    <thead>
                                    <tr>
                                        <th>Patient ID</th>
                                        <th>Name</th>
                                        <th>Birth Date</th>
                                        <th>Address</th>
                                        <th>Gender</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for patient in patient_list %}
                                        <tr>
                                            <td><a href="#" class="patient-detail-link" data-patient-id="{{ patient.id }}">{{ patient.id }}</a></td>
                                            <td>{{ patient.last_name }} {{ patient.first_name }}</td>
                                            <td>{{ patient.birth_date|date:"Ymd" }}</td>
                                            <td>{{ patient.address }}</td>
                                            <td>{{ patient.get_gender_display }}</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            {% else %}
                                <p>환자가 없습니다.</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <!-- 롤 다운을 위한 스타일 -->
                <style>
                    .scrollable-list {
                        max-height: 400px; /* 변경 가능한 높이 설정 */
                        overflow-y: auto;
                    }

                </style>
            </div>
        </div>
    </div>
    <div class="col-md-3" id="patient-detail">
        <!-- 환자 정보가 나타날 곳 -->
        <script>
            // 환자 상세 정보를 가져오는 함수
            function getPatientDetail(patientId) {
                fetch(`/rest/patients/${patientId}/`)  // 적절한 API 엔드포인트로 변경
                    .then(response => response.json())
                    .then(data => {
                        // 받아온 데이터를 화면에 표시
                        const patientDetailDiv = document.getElementById("patient-detail");
                        patientDetailDiv.innerHTML = `
                    <h3>Patient ID: ${data.patient_id}</h3>
                    <p>Name: ${data.first_name} ${data.last_name}</p>
                    <!-- 추가 필드들 표시... -->
                `;
                    })
                    .catch(error => console.error('Error:', error));
            }

            // 각 환자 ID에 대한 클릭 이벤트 리스너 추가
            const patientLinks = document.querySelectorAll(".patient-detail-link");
            patientLinks.forEach(link => {
                link.addEventListener("click", function (event) {
                    event.preventDefault();
                    const patientId = this.getAttribute("data-patient-id");
                    getPatientDetail(patientId);
                });
            });
        </script>
    </div>

    </div>
    <a href="{% url 'base:create_patient' %}" class="btn btn-primary">환자 등록하기</a>
    </div>
{% endblock %}